apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: s-fernandoe-com
  namespace: default
spec:
  secretName: s-fernandoe-com-tls
  issuerRef:
    name: letsencrypt-production
  commonName: s.fernandoe.com
  dnsNames:
  - s.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - s.fernandoe.com
