apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: endereco-ms-fernandoe-com
  namespace: default
spec:
  secretName: endereco-ms-fernandoe-com-tls
  issuerRef:
    name: letsencrypt-production
  commonName: endereco.ms.fernandoe.com
  dnsNames:
  - endereco.ms.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - endereco.ms.fernandoe.com
