apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: "fer.esp@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
